name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v3
    - name: Build
      run: cargo build --release -p phira-mp-server
    - name: capture build artifacts
      uses: actions/upload-artifact@v2
      with:
        name: Artifacts
        path: target/release/phira-mp-server
